// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1vZCoozCNFAo2ueD6dqIA9TX9Zc0ZdIY',
    appId: '1:584796488395:web:569b8b6e09b382c782d14e',
    messagingSenderId: '584796488395',
    projectId: 'weight-tracker-90f93',
    authDomain: 'weight-tracker-90f93.firebaseapp.com',
    storageBucket: 'weight-tracker-90f93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpHO0NIB54KW0bxs-K87Ps3Z7Vd0nSW2k',
    appId: '1:584796488395:android:f5a2d47a767e601682d14e',
    messagingSenderId: '584796488395',
    projectId: 'weight-tracker-90f93',
    storageBucket: 'weight-tracker-90f93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQEhFVF4a7I-NBPF5ZIIe7ZspUVKWxNsg',
    appId: '1:584796488395:ios:09fda864ab34d5f582d14e',
    messagingSenderId: '584796488395',
    projectId: 'weight-tracker-90f93',
    storageBucket: 'weight-tracker-90f93.appspot.com',
    iosBundleId: 'com.example.weightTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQEhFVF4a7I-NBPF5ZIIe7ZspUVKWxNsg',
    appId: '1:584796488395:ios:eaa4e7e0c79418b382d14e',
    messagingSenderId: '584796488395',
    projectId: 'weight-tracker-90f93',
    storageBucket: 'weight-tracker-90f93.appspot.com',
    iosBundleId: 'com.example.weightTracker.RunnerTests',
  );
}
